In [1]:
#pip install numpy
#conda install numpy

In [2]:
import numpy as np

In [3]:
mu_lst=[1,2,3,4,5]
arr=np.array(mu_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [9]:
arr.reshape(0,5)

ValueError: cannot reshape array of size 5 into shape (0,5)

In [20]:
#multinested array
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[3,4,5,6,7]

arr=np.array([list1,list2,list3])

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [12]:
arr.shape

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [14]:
arr.shape

(3, 5)

In [15]:
arr.ndim

2

In [16]:
arr.size

15

## indexing

In [32]:
# accesing the array elements
arr=np.array([1,2,3,4,5,6,7,8,9])

In [18]:
arr[3]

4

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [22]:
arr[1:,2:]

array([[4, 5, 6],
       [5, 6, 7]])

In [23]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [24]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [25]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [26]:
arr[1:,1:4]

array([[3, 4, 5],
       [4, 5, 6]])

In [27]:
arr1=np.arange(0,10)

In [28]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr2=np.arange(0,10,2)

In [30]:
arr2

array([0, 2, 4, 6, 8])

In [31]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [33]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[3:]=100

In [35]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [36]:
arr3=arr

In [37]:
arr3[3:]=500
print(arr3)

[  1   2   3 500 500 500 500 500 500]


In [38]:
arr3=arr.copy()

In [39]:
print(arr)
arr3[3:]=1000
print(arr3)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [42]:
#some conditions very useful in eda
val=2
arr[arr<300]

array([1, 2, 3])

In [43]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
arr1=np.arange(0,10).reshape(2,5)

In [45]:
arr2=np.arange(0,10).reshape(2,5)

In [46]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [47]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
#random distribution
np.random.rand(3,3)

array([[0.71788553, 0.96886756, 0.20735964],
       [0.47276069, 0.57894866, 0.42521319],
       [0.78974399, 0.32917676, 0.20088173]])

In [53]:
np.random.randn(4,4)

array([[ 0.41206671,  1.27095275, -0.51704711, -0.11079483],
       [-1.00983656, -1.20733755, -0.12814512, -0.44025265],
       [ 1.32468407,  1.1903507 , -0.8980984 , -0.03441876],
       [-0.32915856, -0.13331609,  0.21314155, -0.9168816 ]])

In [56]:
np.random.randint(0,100,8).reshape(4,2)

array([[72, 42],
       [89, 77],
       [52, 47],
       [10, 36]])

In [57]:
np.random.random_sample((1,5))

array([[0.08559201, 0.14506917, 0.70969455, 0.09162876, 0.79641874]])

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])

In [3]:
a.shape

(2, 3)

In [4]:
a=np.array([1,2,3,4,5,6])

In [5]:
a[0]

1

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a[:3]

array([1, 2, 3])

In [8]:
a[1:5]

array([2, 3, 4, 5])

In [9]:
a[:5]

array([1, 2, 3, 4, 5])

In [10]:
a[4:]

array([5, 6])

In [11]:
b=a[3:]

In [12]:
b

array([4, 5, 6])

In [13]:
b[0]

4

In [14]:
b[0]=40

In [15]:
a

array([ 1,  2,  3, 40,  5,  6])

In [17]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a[0]

array([1, 2, 3, 4])

In [21]:
a[0:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
a[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [25]:
a[1:3,1:3]=([8,9],[11,12])

In [26]:
a

array([[ 1,  2,  3,  4],
       [ 5,  8,  9,  8],
       [ 9, 11, 12, 12]])

In [27]:
a.ndim

2

In [28]:
c=a*np.pi

In [29]:
c

array([[ 3.14159265,  6.28318531,  9.42477796, 12.56637061],
       [15.70796327, 25.13274123, 28.27433388, 25.13274123],
       [28.27433388, 34.55751919, 37.69911184, 37.69911184]])

In [30]:
a.shape

(3, 4)

In [31]:
a.size

12

In [32]:
a.dtype

dtype('int32')

In [34]:
import math
a.size==math.prod(a.shape)

True

In [35]:
np.zeros(2)

array([0., 0.])

In [36]:
np.zeros(2,int)

array([0, 0])

In [37]:
np.empty(2)

array([0., 0.])

In [38]:
np.empty(2)

array([0., 0.])

In [40]:
np.arange(4)

array([0, 1, 2, 3])

In [41]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [44]:
x=np.ones(2,dtype=np.int64)

In [45]:
x

array([1, 1], dtype=int64)

In [46]:
arr=np.array([2,1,5,3,7,4,6,8])

In [47]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [51]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
a+b

array([ 6,  8, 10, 12])

In [53]:
a.dot(b)

70

In [54]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[5,6,7]])

In [56]:
np.concatenate((x,y),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [60]:
arya=np.array([[[0,1,2,3],
               [4,5,6,7]],
              
              [[0,1,2,3],
              [4,5,6,7]],
              
              [[0,1,2,3],
              [4,5,6,7]]])

In [61]:
arya.ndim

3

In [62]:
arya.shape

(3, 2, 4)

In [63]:
a=np.arange(6)

In [64]:
a

array([0, 1, 2, 3, 4, 5])

In [65]:
b=a.reshape(3,2)

In [66]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [67]:
b=a.reshape(2,3)

In [68]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
np.reshape(a,(1,6),order='c')

array([[0, 1, 2, 3, 4, 5]])

In [71]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [72]:
a2=a[np.newaxis,:]
a2.shape

(1, 6)

In [1]:
import numpy as np

In [2]:
np.random.rand(5)

array([0.07492833, 0.35504078, 0.06417926, 0.93185076, 0.77168035])

In [6]:
data=np.random.randn(5,2)
data

array([[-0.26546507,  0.31443691],
       [-0.07949015, -1.49495939],
       [-1.11361156,  0.73289569],
       [ 0.68401319,  0.53169685],
       [-0.51460923, -1.43676245]])

In [10]:
np.random.randint(5)

1